import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

/** Contracts whose ABI the web app consumes, with the identifier it imports. */
export const EXPORTED_CONTRACTS = [{ name: "Arena", exportName: "arenaAbi" }] as const;

const HEADER = "// Auto-generated by contracts/scripts/lib/exportAbi.ts — do not edit by hand.\n";

/** `../web/src/lib/abi` by default; override with WEB_ABI_DIR (relative to the contracts root). */
export function webAbiDir(hre: HardhatRuntimeEnvironment): string {
  return process.env.WEB_ABI_DIR
    ? path.resolve(hre.config.paths.root, process.env.WEB_ABI_DIR)
    : path.resolve(hre.config.paths.root, "..", "web", "src", "lib", "abi");
}

export function deploymentsDir(hre: HardhatRuntimeEnvironment): string {
  return path.resolve(hre.config.paths.root, "deployments");
}

/**
 * Writes one `<Name>.ts` per contract, the ABI as a `const` array so
 * wagmi/viem infer types. Today that is a single file: `Arena.ts`.
 * Nothing else is written into the web package.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  const outDir = webAbiDir(hre);
  fs.mkdirSync(outDir, { recursive: true });

  for (const { name, exportName } of EXPORTED_CONTRACTS) {
    const artifact = await hre.artifacts.readArtifact(name);
    const body = `${HEADER}export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
    fs.writeFileSync(path.join(outDir, `${name}.ts`), body);
  }

  // eslint-disable-next-line no-console
  console.log(`ABIs exported to ${path.relative(process.cwd(), outDir) || "."}`);
}

export interface DeploymentRecord {
  network: string;
  chainId: number;
  deployer: string;
  owner: string;
  signer: string;
  block: number;
  timestamp: string;
  contracts: {
    Arena: string;
  };
}
